CREATE TABLE {$prefix}minisite_versions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    minisite_id VARCHAR(32) NOT NULL,
    version_number INT UNSIGNED NOT NULL,
    status ENUM('draft','published') NOT NULL,
    label VARCHAR(120) NULL,
    comment TEXT NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at DATETIME NULL,
    source_version_id BIGINT UNSIGNED NULL,
    business_slug VARCHAR(120) NULL,
    location_slug VARCHAR(120) NULL,
    title VARCHAR(200) NULL,
    name VARCHAR(200) NULL,
    city VARCHAR(120) NULL,
    region VARCHAR(120) NULL,
    country_code CHAR(2) NULL,
    postal_code VARCHAR(20) NULL,
    location_point POINT NULL,
    site_template VARCHAR(32) NULL,
    palette VARCHAR(24) NULL,
    industry VARCHAR(40) NULL,
    default_locale VARCHAR(10) NULL,
    schema_version SMALLINT UNSIGNED NULL,
    site_version INT UNSIGNED NULL,
    site_json LONGTEXT NOT NULL,
    search_terms TEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_minisite_version (minisite_id, version_number),
    KEY idx_minisite_status (minisite_id, status),
    KEY idx_minisite_created (minisite_id, created_at)
) ENGINE=InnoDB {$charset};
