---
services:
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      TAR_OPTIONS: --no-same-owner
      WORDPRESS_FS_METHOD: direct
    ports:
      - "8000:80"
    volumes:
      - html_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
  html_data:
