name: Enhanced CI with Dependency Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: # Allow manual triggering

jobs:
  # Dependency checks job
  dependencies:
    name: Dependency Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
    
    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-8.3-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.3-composer-
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Check for outdated dependencies
      run: composer outdated --direct
    
    - name: Run Composer audit
      run: composer audit
    
    - name: Check dependency licenses
      run: composer licenses
    
    - name: Validate composer.json
      run: composer validate --strict
    
    - name: Check for security vulnerabilities
      run: composer security

  # Test matrix job
  test:
    name: Test (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['8.0', '8.1', '8.2', '8.3']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
        coverage: xdebug
    
    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-composer-
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Run PHPUnit tests
      run: composer test
    
    - name: Run PHPStan analysis
      run: composer analyze
    
    - name: Run code style checks
      run: composer lint
    
    - name: Upload coverage reports
      if: matrix.php-version == '8.3'
      uses: codecov/codecov-action@v3
      with:
        file: ./build/coverage/clover.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  # Code quality job
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
    
    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-8.3-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.3-composer-
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Run PHPStan analysis
      run: composer analyze
    
    - name: Run code style checks
      run: composer lint
    
    - name: Run security check
      run: composer security

  # Build verification job
  build:
    name: Build Verification
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
    
    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-8.3-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.3-composer-
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-dev
    
    - name: Validate autoloader
      run: composer dump-autoload --optimize
    
    - name: Check for syntax errors
      run: find src -name "*.php" -exec php -l {} \;
    
    - name: Verify plugin structure
      run: |
        test -f minisite-manager.php
        test -d src
        test -d templates
